// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SugarRes;

{ITE} {RCFileType} {SugarResResource.rc}

{$R 'SugarResResource.res' 'SugarResResource.rc'}

begin
end.
